name: "Execute Regression"
on:
  workflow_dispatch:
  push:
    branches:
      - sample
      - feature/*
jobs:
  setup-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "test-compile"
        run: |
          chmod -R 755 test
          cd test
          ls -lR
          echo "start java compile"
          javac -d bin src/**/*.java
          echo "java compile done"
          ls -lR
          java -version
          echo "Setup done"
      - name: "test-execution"
        run: |
           ls -l
           java -Dfile.encoding=UTF-8 -classpath bin:resources test.testCBA
      - name: "save-test-report"
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: ./target/*