name: "Execute Regression"
on:
  workflow_dispatch:
  push:
    branches:
      - sample
      - feature/*
jobs:
  testexec-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "test-execution"
        run: |
           cd test
           java -Dfile.encoding=UTF-8 -classpath bin:resources test.testCBA
      - name: "test-report"
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test/target/